### PR TITLE
Add `layout` config to mailer

### PR DESCRIPTION
**Pull request by distroid**
Hi, I added `layout` option for mailer.

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
Hi @distroid thanks for this PR can use develop as base branch for your branch? because it seems you created your branch from `master` branch.

**Comment by distroid** [comment]
Hi @AlfonsoUceda, I changed base branch to `develop`

**Comment by AlfonsoUceda** [comment]
Thanks @distroid, to me this is a must have for the mailer.

**Comment by distroid** [comment]
@AlfonsoUceda @davydovanton hi, I need help, after merge develop branch for resolve conflicts, I have problems in specs. Now `mailer.configuration.root` return the wrong path for me (always root folder).
It's problem only in specs, in app all works as expected.

For example, if I print path in `dsl_spec.rb`  
Now:

```ruby
Hanami::Mailer.configuration.root      # ~/mailer/spec/support/fixtures
RenderMailer.configuration.root        # ~/mailer
```

Before merge:

```ruby
Hanami::Mailer.configuration.root      # ~/mailer/spec/support/fixtures
RenderMailer.configuration.root        # ~/mailer/spec/support/fixtures/templates
```

I think it happend after #74

**Comment by distroid** [comment]
@AlfonsoUceda done

**Comment by distroid** [comment]
@jodosha hi, specs failed after rebase, I don't know how fix it. I describe problem in https://github.com/hanami/mailer/pull/73#issuecomment-420775094

**Comment by jodosha** [comment]
@distroid Thanks for this feature. I have one big question to answer: does this imposes the need of having a layout?

With views/templates we usually have a default layout to DRY the HTML markup of the web interface.

---

I discourage to follow the same approach, but to have the opposite strategy: mailers are _layout-less_ by default, and they you'll opt-in for this feature.

In other words, I'm against `hanami new` to generate a default layout for mailers.

---

Please let us to know your thoughts. Thanks. 😄

**Comment by distroid** [comment]
@jodosha I think layout for mailer it's a good practice because you can create footer or\and header for mailer templates.

Ok, if you don't want to generate default layout, I improve current logic for skip layout if a file doesn't exist :)

**Comment by jodosha** [comment]
@distroid 
> Ok, if you don't want to generate default layout, I improve current logic for skip layout if a file doesn't exist :)

That would be awesome. Thanks for taking care of this. 👍 

To make sure it's clear, what I mean is: default mailer should work as it is today. Then a user can decide to opt-in.

**Comment by distroid** [comment]
@jodosha 
> To make sure it's clear, what I mean is: default mailer should work as it is today. Then a user can decide to opt-in.

It's already done

For specs I need your help, because after #74 `RenderMailer.configuration.root` return wrong path, it's always root folder of gem, before this changes all works as expected.

**Pull request closed without merging**
